IND-813 Added merge request functionality for gitlab and incorporated Gitlab PAT Token
hashicorp/terraform-provider-tfmigrate pull request #53
Opened 2024-12-04 07:33 UTC by tanushreegorai

### :hammer_and_wrench: Description

This PR includes the changes made in the `gitops.go` file to add merge request functionality for Gitlab. The provider now accepts either github_token or gitlab_token, retrieved from configuration or environment variables. Depending on the value of RemoteProvider (retrived through `GetServiceProvider` function), the appropriate token (github_token or gitlab_token) is used to authenticate and execute the `CreatePullRequest function`.

### :link: External Links

https://hashicorp.atlassian.net/browse/IND-813

### :+1: Definition of Done

- [ ] Unit tests added?

<img width="929" alt="image" src="https://github.com/user-attachments/assets/523c5d99-19c4-4e43-815d-0c9126c1ac1a">

2024-12-04 10:05 UTC, a-anurag27 submitted a review, later dismissed
Minor changes requested.

2024-12-30 05:06 UTC, tanushreegorai commented on internal/gitops/gitops.go
> +		pr, _, err := client.PullRequests.Create(ctx, repoOwner, repoName, newPR)
Yeah we can do that, the similar thing is done in the CLI codebase where response status code is verified and then pullRequest function return a PR url. Similar thing can be done here.

2024-12-30 05:08 UTC, tanushreegorai commented on internal/gitops/gitops.go
> +	if serviceProvider == "github" {
Yeah, the need is to create a gitUtil file which will have all the utility functions for the git related operations and then call them in gitOperations.go like we already have for the CLI. I'll have a similar kind of implementation here as well.

2025-01-06 04:02 UTC, sujaysamanta requested changes
please make the changes

2025-01-06 04:14 UTC, tanushreegorai commented on internal/gitops/gitops.go
>  	VALID_URL_REGEX       = `^(https?|git)://.*\.git$`
No, I will change it to support both ssh url and https url.

2025-01-13 13:01 UTC, tanushreegorai commented on internal/gitops/gitops.go
> +
yes, we can do that.

2025-01-22 02:16 UTC, sujaysamanta requested changes
- Rename the gitops package to helper package
- move all git-related files under the git package (including the token validator package)
- create a package named vcs in the util package and move the git package inside the VCS package.
- use tf logger to log things instead of hc logger
- use same interfacing technique for creating pull request as well

2025-01-22 02:16 UTC, sujaysamanta commented on internal/util/git/gitUtil.go
> +	logger hclog.Logger
Can we use tf log instead of hclog.logger

2025-01-22 02:16 UTC, sujaysamanta commented on internal/util/git/githubUtil.go
> +	logger hclog.Logger
use tf log

2025-01-22 02:16 UTC, sujaysamanta commented on internal/util/git/gitlabUtil.go
> +	logger hclog.Logger
add tf log instead

2025-01-22 02:16 UTC, sujaysamanta commented on internal/util/token_validator/github_token_validator.go
> +	logger     hclog.Logger
add tf log instead

2025-01-22 06:25 UTC, tanushreegorai commented on .golangci.yml
> -    - exportloopref
Because it has been deprecated , and instead of this I have added `copyloopvar` .

2025-01-22 06:30 UTC, tanushreegorai commented on internal/constants/ui_msg.go
> +	ErrorCreatingBranch = `Error creating or checking out branch %s, err: %v. Terraform Migrate will skip all Git operations.`
@sujaysamanta Do you mean to remove the string "Terraform Migrate will skip all Git operations." ?

2025-01-23 09:20 UTC, tanushreegorai commented on internal/gitops/git_operations.go
> +		return pr.GetHTMLURL(), nil
I have moved the above blocks of code under the if and else-if branches to their separate function implementations, something like CreatePR() in conjunction with interface, but creating a factory similar to token validator implementation would need a refractory of the entire gitUtil package.

I have done something like this:

`func (gitOps *gitOperations) CreatePullRequest(pullRequestParams PullRequestParams) (string, error) {

	// Validate the repository identifier.
	if len(strings.Split(pullRequestParams.RepoIdentifier, "/")) != 2 {
		return "", fmt.Errorf(consts.InvalidRepositoryIdentifier, pullRequestParams.RepoIdentifier)
	}
	
	var remoteServiceProvider *consts.GitServiceProvider
	if remoteServiceProvider, err = gitOps.getVcsProviderName(); err != nil {
		return "", err
	}

	switch *remoteServiceProvider {
	case consts.GitHub:
		pr, err := gitOps.gitUtil.CreateGithubPullRequest(gitUtil.PullRequestParams(pullRequestParams))
		if err != nil {
			return "", err
		}
		return pr.GetHTMLURL(), nil
	case consts.GitLab:
		mr, err := gitOps.gitUtil.CreateGitlabMergeRequest(gitUtil.PullRequestParams(pullRequestParams))
		if err != nil {
			return "", err
		}
		return mr.WebURL, nil
	default:
		return "", fmt.Errorf("%w", cliErrs.ErrGitServiceProviderNotSupported)
	}
}`

2025-01-29 07:57 UTC, sujaysamanta approved these changes
LGTM

2025-01-29 07:57 UTC, merged